import Card from '@/components/Card';
import CardCollapse from '@/components/CardCollapse';
import Layout from '@/components/Layout';
import { selectUserSumValue } from '@/redux/userSummarizeSlice';
import React, { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useSelector } from 'react-redux';

const Compare = () => {
  const { register, handleSubmit } = useForm();
  const [random, setRandom] = useState<number>(0);
  const userSumValue = useSelector(selectUserSumValue);
  const onSubmit = handleSubmit(async (data) => {
    console.log(data);
  });

  const DataObject = [
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Abstract',
      par_id: 0,
      sent_id: 'sent_0_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'The main problem for generating an extractive automatic text summary is to detect the most relevant information in the source document.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Abstract',
      par_id: 0,
      sent_id: 'sent_0_1',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Although, some approaches claim being domain and language independent, they use high dependence knowledge like key-phrases or golden samples for machine-learning approaches.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Abstract',
      par_id: 0,
      sent_id: 'sent_0_2',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In this work, we propose a language-and domain-independent automatic text summarization approach by sentence extraction using an unsupervised learning algorithm.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Abstract',
      par_id: 0,
      sent_id: 'sent_0_3',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Our hypothesis is that an unsupervised algorithm can help for clustering similar ideas (sentences).',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Abstract',
      par_id: 0,
      sent_id: 'sent_0_4',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Then, for composing the summary, the most representative sentence is selected from each cluster.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Abstract',
      par_id: 0,
      sent_id: 'sent_0_5',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Several experiments in the standard DUC-2002 collection show that the proposed method obtains more favorable results than other approaches.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In the last two decades, we have experienced an exponential increase in the electronic text information available for being query.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_1',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'The best example of the hugest and everincreased collection of documents most frequently querying is Internet, with millions of web documents.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_2',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Nowadays, it is common to use Google for retrieving a list of thousands of web pages, but the user has to decide if a document is interesting only with the extracted text where the words of the request query appears.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_3',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Therefore, it is necessary download and read each document until the user finds satisfactory information.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_4',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'It was unnecessary and time-consuming routine.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_5',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Thus, it is indispensable to develop automatic methods for detecting the most relevant content from a source document in order to show it as a summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_6',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In addition, there are a number of scenarios where automatic construction of such summaries is useful.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_7',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Other examples include automatic construction of summaries of news articles or email messages for sending them to mobile devices as SMS; summarization of information for government officials, businesspersons, researches, etc, and summarization of web pages to be shown on the screen of a mobile device, among many others.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_8',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'These examples show that it is desirable that text summarization approaches work more in language and dominion independent way.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_9',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Automatic Text Summarization (ATS) is an active research area that deals with single-and multi-document summarization tasks.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_10',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: "In single-document summarization, the summary of only one document is built, while in multi-document summarization the summary of a whole collection of documents (such as all today's news or all search results for a query) is built.",
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 2,
      sent_id: 'sent_2_11',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'While we believe that our ideas apply to either case, in this work we have experimented only with single-document summaries.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 3,
      sent_id: 'sent_3_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Summarization methods can be classified into abstractive and extractive summarization [1].',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 3,
      sent_id: 'sent_3_1',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'An abstractive summary is an arbitrary text that describes the contexts of the source document.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 3,
      sent_id: 'sent_3_2',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Abstractive summarization process consists of "understanding" the original text and "re-telling" it in fewer words.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 3,
      sent_id: 'sent_3_3',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Namely, an abstractive summarization method uses linguistic methods to examine and interpret the text and then to find new concepts and expressions to best describe it by generating a new shorter text that conveys the most important information from the original document.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 3,
      sent_id: 'sent_3_4',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'While this may seem the best way to construct a summary (and this is how human beings do it), in real-life setting immaturity of the corresponding linguistic technology for text analysis and generation currently renders such methods practically infeasible.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 4,
      sent_id: 'sent_4_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'An extractive summary, in contrast, is composed with a selection of sentences (or phrases, paragraphs, etc) from the original text, usually presented to the user in the same order-ie, a copy of the source text with most sentences omitted.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 4,
      sent_id: 'sent_4_1',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'An extractive summarization method only decides, for each sentence, whether or not it will be included in the summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 4,
      sent_id: 'sent_4_2',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'The resulting summary reads rather awkward; however, simplicity of the underlying statistical techniques makes extractive summarization an attractive, robust, language-independent alternative to more "intelligent" abstractive methods.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 4,
      sent_id: 'sent_4_3',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In this paper, we consider extractive summarization.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 6,
      sent_id: 'sent_6_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'The main problem for generating an extractive automatic text summary is to detect the most relevant information in the source document.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 6,
      sent_id: 'sent_6_1',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Although, some approaches claim being domain and language independent, they use some degree of language knowledge like lexical information [2], key-phrases [3] or golden samples for supervised learning approaches [4][5][6].',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 6,
      sent_id: 'sent_6_2',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Furthermore, training on a specific domain tends to customize the extraction process to that domain, so the resulting classifier is not necessarily portable.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 6,
      sent_id: 'sent_6_3',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In our opinion, these works present a high dominion and language dependence degree.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 7,
      sent_id: 'sent_7_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In this work, we propose a language-and domain-independent automatic text summarization approach by sentence extraction using an unsupervised learning algorithm.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 7,
      sent_id: 'sent_7_1',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Our hypothesis is that an unsupervised algorithm can help for clustering similar ideas (sentences).',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 7,
      sent_id: 'sent_7_2',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Then, for composing the summary, the most representative sentence is selected from each cluster.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Introduction',
      par_id: 7,
      sent_id: 'sent_7_3',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In addition, this approach lets to control in some degree the number of words in the generated summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Related Work',
      par_id: 10,
      sent_id: 'sent_10_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Ideally, a text summarization system should "understand" (analyze) the text and express its main contents by generating the text of the summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Related Work',
      par_id: 10,
      sent_id: 'sent_10_1',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'For example, Cristea et al [9] perform sentence weighting according to their proximity to the central idea of the text, which is determined by analysis of the discourse structure.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Related Work',
      par_id: 12,
      sent_id: 'sent_12_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Supervised learning methods consider sentence selection as classification: they train a classifier using a collection of documents supplied with existing summaries.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Related Work',
      par_id: 12,
      sent_id: 'sent_12_1',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'As features of a sentence, such methods can consider text units (in which case we can speak of term selection) or other, non-lexical characteristics.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Related Work',
      par_id: 12,
      sent_id: 'sent_12_2',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'VillatoroTello et al [4] use as terms n-grams found in the text.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Related Work',
      par_id: 12,
      sent_id: 'sent_12_3',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Kupiec et al [10] use predefined cue phrases (this makes the method language-and domain-dependent) as well as non-lexical features such as the position and length of the sentence; their sentence weighting procedure also includes measuring the overlap of the sentence with the title of the document.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Related Work',
      par_id: 12,
      sent_id: 'sent_12_4',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'HaCohenKerner et al [3] consider many other lexical and non-lexical features, such as the position of the sentence in the paragraph.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'General Scheme of the Proposed Approach',
      par_id: 20,
      sent_id: 'sent_20_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Usually an extractive summarization approach performs term selection, term weighting, sentence weighting, and sentence selection steps.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'General Scheme of the Proposed Approach',
      par_id: 20,
      sent_id: 'sent_20_1',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'However, the strategy of sentence selection step is reduced to simply taking the sentences with highest weight.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'General Scheme of the Proposed Approach',
      par_id: 20,
      sent_id: 'sent_20_2',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Even though this strategy works well for the first ranked sentence, the strategy could lead for sentences similar to the first one to tend to be ranked after the first one; producing redundant sentences in the summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'General Scheme of the Proposed Approach',
      par_id: 20,
      sent_id: 'sent_20_3',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'This problem affects negatively in recall measure.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'General Scheme of the Proposed Approach',
      par_id: 20,
      sent_id: 'sent_20_4',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In this sense, we propose to substitute the sentence weighting and sentence selection steps, with an unsupervised learning algorithm.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'General Scheme of the Proposed Approach',
      par_id: 20,
      sent_id: 'sent_20_5',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Our hypothesis is that an unsupervised learning algorithm could help for automatically detecting the groups of similar sentences from which is selected the most representative sentence; reducing in this way the redundancy in the summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'General Scheme of the Proposed Approach',
      par_id: 20,
      sent_id: 'sent_20_6',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In this section, we describe the general steps that are followed in the proposed approach.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 33,
      sent_id: 'sent_33_0',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In this step, we propose to use an unsupervised algorithm for discovering the groups of sentences with similar meaning.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 33,
      sent_id: 'sent_33_1',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Then, we can select the most representative sentence from each group in order to compose the summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 33,
      sent_id: 'sent_33_2',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'In particular, we propose to use the well-known K-means algorithm, which assumes that the number of clusters is previously known.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 33,
      sent_id: 'sent_33_3',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Sometimes this characteristic is a disadvantage in K-means, however in our proposed approach is an advantage because let to specify the number of groups to create what allowed, at the same time, to estimate the number of words in the final summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 33,
      sent_id: 'sent_33_4',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'For example, if the average of words per sentence is 20 and a user desires a 100-word summary then K-means must create 5 clusters, obviously this is only an estimation of the number of words in the final summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 33,
      sent_id: 'sent_33_5',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'K-means represents each sentence in a vector space model.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 33,
      sent_id: 'sent_33_6',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'So, each document is represented as a vector of features, where the features correspond to the different terms in the document, in this case n-grams.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 34,
      sent_id: 'sent_34_0',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'K-means is based on centroids, which are points in the vector space model calculated as the mean of the objects in a group.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 34,
      sent_id: 'sent_34_1',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'K-means iteration consists in to assign each object to the closest centroid and then the new centroids are recalculated again.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 34,
      sent_id: 'sent_34_2',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'The algorithm finishes when the centroids do not change.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 34,
      sent_id: 'sent_34_3',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'In the beginning, the Kmeans algorithm need seeds as the initial centroids for each group.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 34,
      sent_id: 'sent_34_4',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'Thus, the successful of K-means depends on selecting good initial seeds.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 34,
      sent_id: 'sent_34_5',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Normally, the initial seeds are selected in random way.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 34,
      sent_id: 'sent_34_6',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'In our proposed approach, first sentences are considered as initial seeds, since it is known that the Baseline sentences are good candidate sentences for composing the summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Sentence Selection Using an Unsupervised Learning',
      par_id: 34,
      sent_id: 'sent_34_7',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'For measuring the similarity between two sentences the Euclidean distance is used, defined as:',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Experimental Results',
      par_id: 37,
      sent_id: 'sent_37_0',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Algorithm : In each experiment, we followed the standard sequence of steps:',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Experimental Results',
      par_id: 38,
      sent_id: 'sent_38_0',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Preprocessing: eliminate stop-words, then apply Porter stemming [24]; Term selection: decide which size of n-grams as features are to be used to describe the sentences; Term weighting: decide how the importance of each feature is to be calculated, it can be BOOL, TF, IDF or TFIDF; Sentence clustering: decide the initial seeds for the K-means algorithm, in this case Baseline sentences; Sentence selection: after K-means finishes, select the closest sentence (most representative sentence) to each centroid for composing the summary; The specific settings for each step varied between the experiments and are explained below for each experiment.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Experimental Results',
      par_id: 39,
      sent_id: 'sent_39_0',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'We used the standard DUC 2002 collection [11].',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Experimental Results',
      par_id: 39,
      sent_id: 'sent_39_1',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'In particular, we used the data set of 567 news articles of different length and with different topics.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Experimental Results',
      par_id: 39,
      sent_id: 'sent_39_2',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Each document in the DUC collection is supplied with a set of human-generated summaries provided by two different experts. 1 While each expert was asked to generate summaries of different length, we used only the 100-word variants.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Comparison',
      par_id: 45,
      sent_id: 'sent_45_0',
      automatic_label: 'Result',
      manual_label: 'Result',
      checked: false,
      sent: 'The comparison of the best F-measure results of our proposed approach with the above state-of-the-art approaches is presented in table 4. In this table, it is possible to observe that the difference between the worst and best approach is 0.09251.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Comparison',
      par_id: 45,
      sent_id: 'sent_45_1',
      automatic_label: 'Result',
      manual_label: 'Result',
      checked: false,
      sent: 'It difference was calculate in order to show that a centesimal or millesimal increase in Fmeasure is significant.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Comparison',
      par_id: 45,
      sent_id: 'sent_45_2',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'The difference between Baseline (first) and Ledeneva [11] is 0.00105; and between Ledeneva [11] and TextRank [14] is 0.00051; however, the difference between TextRank [14] and our proposed approach is 0.00456.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Comparison',
      par_id: 45,
      sent_id: 'sent_45_3',
      automatic_label: 'Result',
      manual_label: 'Result',
      checked: false,
      sent: 'In addition, we calculate the difference between recall and precision in order to show how our proposed method gets the best balance between recall and precision.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Comparison',
      par_id: 45,
      sent_id: 'sent_45_4',
      automatic_label: 'Result',
      manual_label: 'Result',
      checked: false,
      sent: 'In addition, it is interesting to observe that, in comparison with Baseline (first), our approach obtained better recall results in all the experiments, while the precision was worse in all the experiments.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Comparison',
      par_id: 45,
      sent_id: 'sent_45_5',
      automatic_label: 'Result',
      manual_label: 'Result',
      checked: false,
      sent: 'Nevertheless, our proposed approach obtains better F-measure results than Baseline (first), except for 1-gram and BOOL weighting.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Comparison',
      par_id: 45,
      sent_id: 'sent_45_6',
      automatic_label: 'Claim',
      manual_label: 'Claim',
      checked: false,
      sent: 'It is good to mention the best recall result was obtained by our proposed approach.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 46,
      sent_id: 'sent_46_0',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'In this work, we proposed an extractive automatic text summarization approach by sentence extraction using an unsupervised learning algorithm.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 46,
      sent_id: 'sent_46_1',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'In particular, the Kmeans algorithm for creating groups of similar sentences was used.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 46,
      sent_id: 'sent_46_2',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Then, from the groups of sentences, the most representative sentence was selected for composing the summary.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 46,
      sent_id: 'sent_46_3',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'Normally, the definition of the number of groups to form and the initial seeds of the groups are considered as disadvantages of K-means.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 46,
      sent_id: 'sent_46_4',
      automatic_label: 'Method',
      manual_label: 'Method',
      checked: false,
      sent: 'However, these parameters are used to take advantage of Baseline sentences in order to improve the quality of the summaries.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 46,
      sent_id: 'sent_46_5',
      automatic_label: 'Conclusion',
      manual_label: 'Conclusion',
      checked: false,
      sent: 'The proposed approach, in contrast to supervised methods, does not need large amount of golden samples for training.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 46,
      sent_id: 'sent_46_6',
      automatic_label: 'Result',
      manual_label: 'Result',
      checked: false,
      sent: 'Therefore, our proposed approach is more independent from language and dominion.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 47,
      sent_id: 'sent_47_0',
      automatic_label: 'Result',
      manual_label: 'Result',
      checked: false,
      sent: 'According to experimental results we demonstrate that the proposed approach obtains more favorable results than others state-of-the-art approaches; ranking our proposed approach in second place, very close to the first place.',
      correct_section_head: true,
    },
    {
      user_paper_id: 30,
      paper_name: 'rtyrty',
      section_name: 'Discussion and Conclusions',
      par_id: 47,
      sent_id: 'sent_47_1',
      automatic_label: 'Result',
      manual_label: 'Result',
      checked: false,
      sent: 'In addition, our proposed approach outperforms the Baseline (first) heuristic for F-measure results, except for 1gram and BOOL weighting.',
      correct_section_head: true,
    },
  ];

  const Dummy = [
    { data: 0, type: 'user', text: 'Ini data user' },
    { data: 1, type: 'longsumm', text: 'Ini data longsumm' },
  ];

  useEffect(() => {
    setRandom(Math.random() >= 0.5 ? 1 : 0);
  }, []);


  return (
    <Layout>
      <div className='mt-24 px-5'>
        <div className='flex w-3/5 mx-auto flex-col'>
          <Card title={'Summary Rating'}>
            <form onSubmit={onSubmit}>
              <h3 className='text-lg font-medium mb-2'>
                After reading the generated summaries, please choose which
                summary gives a better overview of the article and write down
                any comments you have. Then submit your answer.
              </h3>
              <div className='form-control items-start'>
                <label className='label cursor-pointer'>
                  <input
                    type='radio'
                    className={`radio`}
                    value={Dummy[random].type}
                    defaultChecked
                    {...register('summary')}
                  />
                  <span className='label-text ml-2'>Summary A</span>
                </label>
              </div>
              <div className='form-control items-start mb-2'>
                <label className='label cursor-pointer'>
                  <input
                    type='radio'
                    className={`radio`}
                    value={random === 0 ? Dummy[1].type : Dummy[0].type}
                    {...register('summary')}
                  />
                  <span className='label-text ml-2'>Summary B</span>
                </label>
              </div>
              <div className='form-control mb-2'>
                <textarea
                  className='textarea textarea-bordered'
                  placeholder='Write your comment here'
                  {...register('comment')}
                />
              </div>
              <button className='btn btn-primary' onClick={() => console.log(DataObject)
              }>Submit</button>
            </form>
          </Card>
          <CardCollapse title={`Summary A`}>{Dummy[random].text}</CardCollapse>
          <CardCollapse title={'Summary B'}>
            {random === 0 ? Dummy[1].text : Dummy[0].text}
          </CardCollapse>
        </div>
      </div>
    </Layout>
  );
};

export default Compare;
