name: Server Deployment
on:
  push:
    branches: [main]

jobs:
  Build-Check-Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./backend"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Installing Dependencies
        run: go run main.go
  Build-Check-Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing Dependencies
        run: yarn install
      - name: Trying to Build
        run: yarn build
  DeployFrontend:
    needs: [Build-Check-Frontend, Build-Check-Backend]
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: /Users/fanzru/skripsi/web-anotasi-paper/frontend/scripts
    steps:
      - uses: actions/checkout@v2
      - name: Preparing to deploy to production 🚀🤘
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd ~/skripsi/web-anotasi-paper/frontend/scripts
            chmod +x deploy.sh
            ./deploy.sh
            cd ~/skripsi/web-anotasi-paper/backend/scripts
            chmod +x deploy.sh
            ./deploy.sh
            